/**
 * Created by Olejka on 09.03.2017.
 */

export { AUTH_SUCCESS, SET_USER, LOGOUT } from './auth'
export {
    SEARCH_VACANCIES,

    FETCH_VACANCIES,
    FETCH_VACANCIES_PENDING,
    FETCH_VACANCIES_SUCCESS,
    FETCH_VACANCIES_ERROR,

    FETCH_REGION_LIST,
    FETCH_REGION_LIST_PENDING,
    FETCH_REGION_LIST_ERROR,
    FETCH_REGION_LIST_SUCCESS,

    FETCH_RESOURCE_LIST,
    FETCH_RESOURCE_LIST_PENDING,
    FETCH_RESOURCE_LIST_SUCCESS,
    FETCH_RESOURCE_LIST_ERROR

} from './vacancies'