/**
 * Created by Olejka on 15.04.2017.
 */

export const  FETCH_REGION_LIST = "FETCH_REGION_LIST";
export const  FETCH_REGION_LIST_PENDING = "FETCH_REGION_LIST_PENDING";
export const  FETCH_REGION_LIST_SUCCESS = "FETCH_REGION_LIST_SUCCESS";
export const  FETCH_REGION_LIST_ERROR = "FETCH_REGION_LIST_ERROR";
