/**
 * Created by Olejka on 15.04.2017.
 */


export const  FETCH_RESOURCE_LIST = "FETCH_RESOURCE_LIST";
export const  FETCH_RESOURCE_LIST_PENDING= "FETCH_RESOURCE_LIST_PENDING";
export const  FETCH_RESOURCE_LIST_SUCCESS = "FETCH_RESOURCE_LIST_SUCCESS";
export const  FETCH_RESOURCE_LIST_ERROR = "FETCH_RESOURCE_LIST_ERROR";