/**
 * Created by Olejka on 15.04.2017.
 */

export const GET_VACANCY_INFO = "GET_VACANCY_INFO";

export const FETCH_VACANCY_INFO = "FETCH_VACANCY_INFO";
export const FETCH_VACANCY_INFO_SUCCESS = "FETCH_VACANCY_INFO_SUCCESS";
export const FETCH_VACANCY_INFO_PENDING = "FETCH_VACANCY_INFO_PENDING";
export const FETCH_VACANCY_INFO_ERROR = "FETCH_VACANCY_INFO_ERROR";