/**
 * Created by Olejka on 10.04.2017.
 */

export const  SEARCH_VACANCIES = "SEARCH_VACANCIES";

export const  FETCH_VACANCIES = "FETCH_VACANCIES";
export const  FETCH_VACANCIES_PENDING = "FETCH_VACANCIES_PENDING";
export const  FETCH_VACANCIES_SUCCESS = "FETCH_VACANCIES_SUCCESS";
export const  FETCH_VACANCIES_ERROR = "FETCH_VACANCIES_ERROR";

export const  FETCH_VACANCIES_WEEKDAY = "FETCH_VACANCIES_WEEKDAY";
export const  FETCH_VACANCIES_WEEKDAY_SUCCESS = "FETCH_VACANCIES_WEEKDAY_SUCCESS";
export const  FETCH_VACANCIES_WEEKDAY_PENDING = "FETCH_VACANCIES_WEEKDAY_PENDING";
export const  FETCH_VACANCIES_WEEKDAY_ERROR = "FETCH_VACANCIES_WEEKDAY_ERROR";